require("lazy").setup({
  require("plugins/blink"),
  require("plugins/debug"),
  require("plugins/gitsigns"),
  require("plugins/mason"),
  require("plugins/lualine"),
  require("plugins/mini-starter"),
  require("plugins/neogit"),
  require("plugins/noice"),
  require("plugins/rainbow-csv"),
  require("plugins/telescope"),
  require("plugins/theme"),
  require("plugins/todo-comments"),
  require("plugins/treesitter"),
  require("plugins/which"),
  require("plugins/hardtime"),
  require("plugins/opencode"),
  require("plugins/yazi")
})
-- vim: ts=2 sts=2 sw=2 et
